name: PyPI Publish

on:
  repository_dispatch:
    types: [pypi-release]

permissions:
  contents: read

jobs:
  pypi-release:
    runs-on: ubuntu-latest
    concurrency:
      group: pypi-${{ github.event.client_payload.tag_name }}
      cancel-in-progress: true
    permissions:
      id-token: write # Generate OIDC token for attestations
      attestations: write # Attest the build provenance
    environment:
      name: pypi
      url: https://pypi.org/p/richforms
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit
      -
        name: Echo Build Dispatch
        run: |
          echo "PyPI Release Triggered"
          echo "Event Payload: ${{ toJson(github.event.client_payload) }}"
      -
        name: Checkout Code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          ref: ${{ github.event.client_payload.tag_name }}
      -
        name: Install uv
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
        with:
          enable-cache: false
      -
        name: Set up Python
        run: uv python install 3.13
      -
        name: Build release distributions
        run: uv build
      -
        name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          attestations: true
          packages-dir: dist/
          verbose: true
          print-hash: true
      -
        name: Attestations for PYPI Wheel
        uses: actions/attest-build-provenance@e8998f949152b193b063cb0ec769d69d929409be # v2.4.0
        with:
          subject-path: |
            dist/*.whl
          subject-name: richforms-wheel
          show-summary: true
      -
        name: Attestations for PYPI Source
        uses: actions/attest-build-provenance@e8998f949152b193b063cb0ec769d69d929409be # v2.4.0
        with:
          subject-path: |
            dist/*.tar.gz
          subject-name: richforms-source
          show-summary: true
