name: Release Automation

on:
  push:
    branches: [main]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - id: release
        uses: googleapis/release-please-action@v4.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
      - name: Dispatch PYPI Release
        if: ${{ steps.release.outputs.release_created }}
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          repository: shinybrar/richforms
          event-type: pypi-release
          token: ${{ secrets.GITHUB_TOKEN }}
          client-payload: |-
            {
              "releases_created": "${{ steps.release.outputs.releases_created }}",
              "tag_name": "${{ steps.release.outputs.tag_name }}",
              "sha": "${{ steps.release.outputs.sha }}"
            }
